### PR TITLE
Stop player on completion

### PR DESCRIPTION
**Pull request by meeoh**
Was poking around, heres a way that the player can automatically stop when done playing. Right now the user has to setup a playback listener and do that manually.

The approach I took was to unconditionally add an event listener when play is pressed, and if `addPlayBackListener` has been called, then we'll call that as apart of our event listener. This way, we can do some additional logic in our event listener (e.g check if duration === currentPosition), while still having only one event listener overall.

Another approach would of been to add a completely separate event listener for internal use only.

### CODE REVIEW

**Comment by rafalzawadzki** [comment]
@meeoh thank you for looking into this!

I tested your changes and they indeed work, but only on the first play. After the first play is completed, the issue persists for the consecutive ones. The duration !== currentPosition, so it's not possible to figure out that playback has stopped.

Do you have an idea how to accomplish this?

**Comment by meeoh** [comment]
@rafalzawadzki Were you testing on iOS or android? I tried on iOS and I was able to press play, it would play till completion then get stopped. And when I would press play again it would work fine 😕

**Review by hyochan — APPROVED** [review]
@meeoh Looks great. I've just updated small codebase in addition to your `PR`. Also updated `Example` project just by removing unnecessary `stop` in callback listener.

@rafalzawadzki  Thank you for testing it out. However, it did not occur any problem on my side. Maybe you've not `build` the typescript before actually install the module from `file../`?

Approve this PR! Great work again.

**Comment by milesscherrer** [comment]
Would be great to have a onPlaybackStopped event to trigger logic when playback finishes, how could I do that?

**Comment by shameelabd** [comment]
> Would be great to have a onPlaybackStopped event to trigger logic when playback finishes, how could I do that?

This PR is already merged so wont be apart of it @milesscherrer. However if you add a playback listener, you can just wait for `currentPosition === duration` and run your logic on that

**Comment by meeoh** [comment]
> Would be great to have a onPlaybackStopped event to trigger logic when playback finishes, how could I do that?

This PR is already merged so wont be apart of it @milesscherrer. However if you add a playback listener, you can just wait for `currentPosition === duration` and run your logic on that

**Comment by rafalzawadzki** [comment]
> Would be great to have a onPlaybackStopped event to trigger logic when playback finishes, how could I do that?

I second that! Considering [this issue](https://github.com/hyochan/react-native-audio-recorder-player/issues/328#issuecomment-876325133), it's not possible to reliably trigger "on stop" logic

**Comment by brerdem** [comment]
Anybody found an effective solution/workaround for this?

**Pull request merged**
