### PR TITLE
#574 - fix Android RN 0.73.0 support

### PR DESCRIPTION
**Pull request by idanlevi1**
Fixes https://github.com/hyochan/react-native-audio-recorder-player/issues/574 
@hyochan

### CODE REVIEW

**Comment by Rossella-Mascia-Neosyn** [comment]
When will the pull request be accepted?

**Comment by bigriot** [comment]
I don't want to sound naggy, but I really really need this to be applied ASAP.

**Comment by Rossella-Mascia-Neosyn** [comment]
@bigriot have you tried doing what they say here https://github.com/hyochan/react-native-audio-recorder-player/issues/574 ?
did you have any errors?

**Review by hyochan — APPROVED** [review]
LGTM!

**Pull request merged**
