### PR TITLE
New AVModeIOS audio setting

### PR DESCRIPTION
**Pull request by udfalkso**
I had the need to use measurement mode while recording background audio.  I thought others may have similar needs.  This PR adds a new mode setting for ios.  

Thanks for the great lib!  Please let me know if I need to adjust this PR in any way.

### CODE REVIEW

**Review by hyochan — CHANGES_REQUESTED** [review]
@udfalkso 
Hello! Thanks for your great contribution!

Could you kindly fix the `CI` failing?

**Comment by udfalkso** [comment]
How's it look now?

**Comment by hyochan** [comment]
> How's it look now?

Still failing on `tsc`. It will automatically run on next commit I think.

**Comment by udfalkso** [comment]
Sorry I think I got it this time.  Thanks

**Review by hyochan — APPROVED** [review]
LGTM!

**Pull request merged**
