### PR TITLE
Reset MediaPlayer on Stop and Completion in Android

### PR DESCRIPTION
**Pull request by efstathiosntonas**

### CODE REVIEW

**Review by hyochan — COMMENTED** [review]
@efstathiosntonas Thank you for your contribution to this! Could you kindly explain the result of having `reset` after `stop`?

**Comment by efstathiosntonas** [comment]
@hyochan I've looked into other Android projects that utilized MediaPlayer and most of them reset the player. 

Besides that, here is a part from the [docs](https://developer.android.com/reference/android/media/MediaPlayer): 

> There is a subtle but important difference between a newly constructed MediaPlayer object and the MediaPlayer object after [reset()](https://developer.android.com/reference/android/media/MediaPlayer#reset()) is called. It is a programming error to invoke methods such as [getCurrentPosition()](https://developer.android.com/reference/android/media/MediaPlayer#getCurrentPosition()), [getDuration()](https://developer.android.com/reference/android/media/MediaPlayer#getDuration()), [getVideoHeight()](https://developer.android.com/reference/android/media/MediaPlayer#getVideoHeight()), [getVideoWidth()](https://developer.android.com/reference/android/media/MediaPlayer#getVideoWidth()), [setAudioAttributes(android.media.AudioAttributes)](https://developer.android.com/reference/android/media/MediaPlayer#setAudioAttributes(android.media.AudioAttributes)), [setLooping(boolean)](https://developer.android.com/reference/android/media/MediaPlayer#setLooping(boolean)), [setVolume(float, float)](https://developer.android.com/reference/android/media/MediaPlayer#setVolume(float,%20float)), [pause()](https://developer.android.com/reference/android/media/MediaPlayer#pause()), [start()](https://developer.android.com/reference/android/media/MediaPlayer#start()), [stop()](https://developer.android.com/reference/android/media/MediaPlayer#stop()), [seekTo(long, int)](https://developer.android.com/reference/android/media/MediaPlayer#seekTo(long,%20int)), [prepare()](https://developer.android.com/reference/android/media/MediaPlayer#prepare()) or [prepareAsync()](https://developer.android.com/reference/android/media/MediaPlayer#prepareAsync()) in the Idle state for both cases. If any of these methods is called right after a MediaPlayer object is constructed, the user supplied callback method OnErrorListener.onError() won't be called by the internal player engine and the object state remains unchanged; but if these methods are called right after [reset()](https://developer.android.com/reference/android/media/MediaPlayer#reset()), the user supplied callback method OnErrorListener.onError() will be invoked by the internal player engine and the object will be transfered to the Error state

**Review by hyochan — APPROVED** [review]
Screenshot 2023-10-31 at 8 34 03 PM

Here's ChatGPT's response to this. According to it, we can skip it. However, considering that in this module, the `mediaPlayer` is reused in every scenario, I think it would be a good idea to include `reset` in each step.

LGTM!

**Comment by efstathiosntonas** [comment]
perfect! thanks @hyochan

**Pull request merged**
