### PR TITLE
Fix MediaPlayer Position Access Issue

### PR DESCRIPTION
**Pull request by efstathiosntonas**
probably fixes https://github.com/hyochan/react-native-audio-recorder-player/issues/557

### CODE REVIEW

**Review by hyochan — CHANGES_REQUESTED** [review]
@efstathiosntonas Thank you for your PR and this is really insightful 👀 

Although the added isPlaying check prevents inaccurate event emissions, the current implementation still schedules mTask via mTimer, potentially utilizing system resources even when not playing.

I think the code should be changed as below to be more idealistic.

```
@ReactMethod
fun pausePlayer(promise: Promise) {
    ...
    mTimer?.cancel()  // Cancel TimerTask to prevent unnecessary resource usage.
    ...
}

@ReactMethod
fun resumePlayer(promise: Promise) {
    ...
    // Re-schedule TimerTask only upon resumption to ensure resource efficiency.
    mTimer = Timer()
    mTimer!!.schedule(mTask, 0, subsDurationMillis.toLong())
    ...
}
```

How do you think?

**Comment by efstathiosntonas** [comment]
@hyochan your knowledge in this is better than mine since I do not know kotlin/java, I'll do whatever you think best.

**Comment by efstathiosntonas** [comment]
@hyochan I think we need to recreate the `mTask` inside the resumePlayer otherwise it will throw `Task already scheduled or cancelled`, what do you think?

something like this:

```kt
    @ReactMethod
    fun resumePlayer(promise: Promise) {
        if (mediaPlayer == null) {
            promise.reject("resume", "mediaPlayer is null on resume.")
            return
        }

        if (mediaPlayer!!.isPlaying) {
            promise.reject("resume", "mediaPlayer is already running.")
            return
        }

        try {
            mTimer = Timer()
            mediaPlayer!!.seekTo(mediaPlayer!!.currentPosition)
            mTask = object : TimerTask() {
                override fun run() {
                    val obj = Arguments.createMap()
                    obj.putInt("duration", mediaPlayer!!.duration)
                    obj.putInt("currentPosition", mediaPlayer!!.currentPosition)
                    sendEvent(reactContext, "rn-playback", obj)
                }
            }
            mTimer!!.schedule(mTask, 0, subsDurationMillis.toLong())
            mediaPlayer!!.start()
            promise.resolve("resume player")
        } catch (e: Exception) {
            Log.e(tag, "mediaPlayer resume: " + e.message)
            promise.reject("resume", e.message)
        }
    }

    @ReactMethod
    fun pausePlayer(promise: Promise) {
        if (mediaPlayer == null) {
            promise.reject("pausePlay", "mediaPlayer is null on pause.")
            return
        }

        try {
            mediaPlayer!!.pause()
            mTimer?.cancel()
            promise.resolve("pause player")
        } catch (e: Exception) {
            Log.e(tag, "pausePlay exception: " + e.message)
            promise.reject("pausePlay", e.message)
        }
    }
```

**Comment by efstathiosntonas** [comment]
@hyochan after applying the patch above I still get the [crash](https://github.com/hyochan/react-native-audio-recorder-player/issues/557), without the patch the amount of crashes was higher though 🤔

**Comment by efstathiosntonas** [comment]
@hyochan I've wrapped it in a try/catch, at least it will silence the error. I really don't know what else to do with this one. 

```diff
@@ -231,13 +233,19 @@ class RNAudioRecorderPlayerModule(private val reactContext: ReactApplicationCont
                  */
                 mTask = object : TimerTask() {
                     override fun run() {
-                        val obj = Arguments.createMap()
-                        obj.putInt("duration", mp.duration)
-                        obj.putInt("currentPosition", mp.currentPosition)
-                        sendEvent(reactContext, "rn-playback", obj)
+                       try {
+                           val obj = Arguments.createMap()
+                           obj.putInt("duration", mp.duration)
+                           obj.putInt("currentPosition", mp.currentPosition)
+                           sendEvent(reactContext, "rn-playback", obj)
+                       } catch (e: IllegalStateException) {
+                           // Handle the exception
+                           Log.e(tag, "MediaPlayer is not in a valid state", e)
+                       }
                     }
                 }

+                mTimer?.cancel()
                 mTimer = Timer()
                 mTimer!!.schedule(mTask, 0, subsDurationMillis.toLong())
                 val resolvedPath = if (((path == "DEFAULT"))) "${reactContext.cacheDir}/$defaultFileName" else path
```

**Comment by hyochan** [comment]
> @hyochan I've wrapped it in a try/catch, at least it will silence the error and avoid crash. I really don't know what else to do with this one.
> 
> ```diff
> @@ -231,13 +233,19 @@ class RNAudioRecorderPlayerModule(private val reactContext: ReactApplicationCont
>                   */
>                  mTask = object : TimerTask() {
>                      override fun run() {
> -                        val obj = Arguments.createMap()
> -                        obj.putInt("duration", mp.duration)
> -                        obj.putInt("currentPosition", mp.currentPosition)
> -                        sendEvent(reactContext, "rn-playback", obj)
> +                       try {
> +                           val obj = Arguments.createMap()
> +                           obj.putInt("duration", mp.duration)
> +                           obj.putInt("currentPosition", mp.currentPosition)
> +                           sendEvent(reactContext, "rn-playback", obj)
> +                       } catch (e: IllegalStateException) {
> +                           // Handle the exception
> +                           Log.e(tag, "MediaPlayer is not in a valid state", e)
> +                       }
>                      }
>                  }
> 
> +                mTimer?.cancel()
>                  mTimer = Timer()
>                  mTimer!!.schedule(mTask, 0, subsDurationMillis.toLong())
>                  val resolvedPath = if (((path == "DEFAULT"))) "${reactContext.cacheDir}/$defaultFileName" else path
> ```

I have managed to handle this in [c5ef0f1](https://github.com/hyochan/react-native-audio-recorder-player/pull/558/commits/c5ef0f1fe51697d5ca11254ffc182c2b099b96af). Let's see what happens 🤔

**Review by hyochan — APPROVED** [review]

**Review by hyochan — APPROVED** [review]

**Comment by efstathiosntonas** [comment]
thanks @hyochan, keep it up!

**Pull request merged**
