### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by spencerchubb**
rn-fetch-blob is no longer maintained, so it may be wise to recommend react-native-blob-util

"The project will be continued in this repository. React-Native-Blob-Util is fully compatible with RN-Fetch-Blob and React-Native-Fetch-Blob."

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
@spencerchubb I think we could include [react-native-file-access](https://github.com/alpha0010/react-native-file-access) as another option too, I've been using it since day 1 with 0 issues and it's well mentained.

**Review by hyochan — APPROVED** [review]
LGTM!

**Comment by hyochan** [comment]
> @spencerchubb I think we could include [react-native-file-access](https://github.com/alpha0010/react-native-file-access) as another option too, I've been using it since day 1 with 0 issues and it's well maintained.

Could you kindly open `PR` for this too?

**Comment by efstathiosntonas** [comment]
@hyochan there you go: https://github.com/hyochan/react-native-audio-recorder-player/pull/613

**Pull request merged**
